
function generateHeader() {
    return [
        '//===========================================================================',
        '//',
        '// Just another Warcraft III map',
        '//',
        '//   Warcraft III map script',
        '//   Generated by the Warcraft III World Editor',
        '//   Date: Sat Aug 12 13:08:29 2017',
        '//   Map Author: Unknown',
        '//',
        '//==========================================================================='
    ].join('\r\n');
}

function generateGlobalBlock(globalArray) {
    return [
        '//***************************************************************************',
        '//*',
        '//*  Global Variables',
        '//*',
        '//***************************************************************************'
    ].join('\r\n') +
    '\r\n\r\n' +

    'globals\r\n' +
    '    // Generated\r\n' +
    '    trigger                 gg_trg_Melee_Initialization = null\r\n' +
    globalArray.join('\r\n') +
    '\r\nendglobals' + '\r\n\r\n' + `function InitGlobals takes nothing returns nothing\r\nendfunction`
}

function generateUnitCreationBlock() {
    return [
        '//***************************************************************************',
        '//*',
        '//*  Unit Creation',
        '//*',
        '//***************************************************************************',
        '',
        '//===========================================================================',
        'function CreateUnitsForPlayer0 takes nothing returns nothing',
        '    local player p = Player(0)',
        '    local unit u',
        '    local integer unitID',
        '    local trigger t',
        '    local real life',
        '',
        '    set u = CreateUnit( p, \'nwgs\', 19.4, 147.4, 161.207 )',
        'endfunction',
        '',
        '//===========================================================================',
        'function CreatePlayerBuildings takes nothing returns nothing',
        'endfunction',
        '',
        '//===========================================================================',
        'function CreatePlayerUnits takes nothing returns nothing',
        '    call CreateUnitsForPlayer0(  )',
        'endfunction',
        '',
        '//===========================================================================',
        'function CreateAllUnits takes nothing returns nothing',
        '    call CreatePlayerBuildings(  )',
        '    call CreatePlayerUnits(  )',
        'endfunction'
    ].join('\r\n');
}

function generateTriggerBlock(triggerArray) {
    var output = [
        '//***************************************************************************',
        '//*',
        '//*  Triggers',
        '//*',
        '//***************************************************************************',
        '',
        '//===========================================================================',
        '// Trigger: Melee Initialization',
        '//',
        '// Default melee game initialization for all players',
        '//===========================================================================',
        'function Trig_Melee_Initialization_Actions takes nothing returns nothing',
        '    call MeleeStartingVisibility(  )',
        '    call MeleeStartingHeroLimit(  )',
        '    call MeleeGrantHeroItems(  )',
        '    call MeleeStartingResources(  )',
        '    call MeleeClearExcessUnits(  )',
        '    call MeleeStartingUnits(  )',
        '    call MeleeStartingAI(  )',
        '    call MeleeInitVictoryDefeat(  )',
        'endfunction',
        '',
        '//===========================================================================',
        'function InitTrig_Melee_Initialization takes nothing returns nothing',
        '    set gg_trg_Melee_Initialization = CreateTrigger(  )',
        '    call TriggerAddAction( gg_trg_Melee_Initialization, function Trig_Melee_Initialization_Actions )',
        'endfunction',
        '',
        '//===========================================================================',
        'function InitCustomTriggers takes nothing returns nothing',
        '    call InitTrig_Melee_Initialization(  )',
        'endfunction',
        '',
        '//===========================================================================',
        'function RunInitializationTriggers takes nothing returns nothing',
        '    call ConditionalTriggerExecute( gg_trg_Melee_Initialization )',
        'endfunction'
    ].join('\r\n');

    output += '\r\n\r\n';

    triggerArray.forEach((trigger) => {
        output += '//===========================================================================\r\n';
        output += trigger;
        output += '\r\n\r\n';
    });

    console.log('# triggers', triggerArray.length);

    return output;
}

function generatePlayers() {
    return [
        '//***************************************************************************',
        '//*',
        '//*  Players',
        '//*',
        '//***************************************************************************',
        '',
        'function InitCustomPlayerSlots takes nothing returns nothing',
        '',
        '    // Player 0',
        '    call SetPlayerStartLocation( Player(0), 0 )',
        '    call SetPlayerColor( Player(0), ConvertPlayerColor(0) )',
        '    call SetPlayerRacePreference( Player(0), RACE_PREF_HUMAN )',
        '    call SetPlayerRaceSelectable( Player(0), true )',
        '    call SetPlayerController( Player(0), MAP_CONTROL_USER )',
        '',
        'endfunction',
        '',
        'function InitCustomTeams takes nothing returns nothing',
        '    // Force: TRIGSTR_002',
        '    call SetPlayerTeam( Player(0), 0 )',
        '',
        'endfunction'
    ].join('\r\n');
}

function generateMain() {
    return [
        '//***************************************************************************',
        '//*',
        '//*  Main Initialization',
        '//*',
        '//***************************************************************************',
        '',
        '//===========================================================================',
        'function main takes nothing returns nothing',
        '    call SetCameraBounds( -3328.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -3584.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 3328.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 3072.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -3328.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 3072.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 3328.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -3584.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM) )',
        '    call SetDayNightModels( "Environment\\\\DNC\\\\DNCLordaeron\\\\DNCLordaeronTerrain\\\\DNCLordaeronTerrain.mdl", "Environment\\\\DNC\\\\DNCLordaeron\\\\DNCLordaeronUnit\\\\DNCLordaeronUnit.mdl" )',
        '    call NewSoundEnvironment( "Default" )',
        '    call SetAmbientDaySound( "LordaeronSummerDay" )',
        '    call SetAmbientNightSound( "LordaeronSummerNight" )',
        '    call SetMapMusic( "Music", true, 0 )',
        '    call CreateAllUnits(  )',
        '    call InitBlizzard(  )',
        '    call InitGlobals(  )',
        '    call InitCustomTriggers(  )',
        '    call RunInitializationTriggers(  )',
        '',
        'endfunction'
    ].join('\r\n');
}

function generateConfig() {
    return [
        '//***************************************************************************',
        '//*',
        '//*  Map Configuration',
        '//*',
        '//***************************************************************************',
        '',
        'function config takes nothing returns nothing',
        '    call SetMapName( "Just another Warcraft III map" )',
        '    call SetMapDescription( "Nondescript" )',
        '    call SetPlayers( 1 )',
        '    call SetTeams( 1 )',
        '    call SetGamePlacement( MAP_PLACEMENT_USE_MAP_SETTINGS )',
        '',
        '    call DefineStartLocation( 0, -960.0, -2432.0 )',
        '',
        '    // Player setup',
        '    call InitCustomPlayerSlots(  )',
        '    call SetPlayerSlotAvailable( Player(0), MAP_CONTROL_USER )',
        '    call InitGenericPlayerSlots(  )',
        'endfunction'
    ].join('\r\n');
}

module.exports = function(mapObj, declarations) {
    var output = '',
        NL = '\r\n';

    output += generateHeader() + NL + NL;
    output += generateGlobalBlock(declarations.globals) + NL + NL;
    output += generateUnitCreationBlock() + NL + NL;
    output += generateTriggerBlock(declarations.functions) + NL + NL;
    output += generatePlayers() + NL + NL;
    output += generateMain() + NL + NL;
    output += generateConfig() + NL + NL;

    return output;
};
